src/dashboard/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

from .views import (
                    home,
                    events_main,
                    events_detail,
                    EventsCreateView,
                    EventsUpdateView,
                    EventsDeleteView,
                    SnivelCreateView,
                    SnivelUpdateView,
                    SnivelDeleteView,
                    SnivelMasterUpdateView,
                    SnivelMasterDeleteView

                    )


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^events_manager/$', events_main, name='events_main'),
    url(r'^events_manager/(?P<pk>\d+)/$', events_detail, name='events_detail'),
    url(r'^events_manager/create/$', EventsCreateView.as_view(), name='events_create'),    
    url(r'^events_manager/(?P<pk>\d+)/update/$', EventsUpdateView.as_view(), name='events_update'),
    url(r'^events_manager/(?P<pk>\d+)/delete/$', EventsDeleteView.as_view(), name='events_delete'),
    url(r'^snivel/create/$', SnivelCreateView.as_view(), name='snivel_create'),
    url(r'^snivel/(?P<pk>\d+)/update/$', SnivelUpdateView.as_view(), name='snivel_update'),
    url(r'^snivel/(?P<pk>\d+)/master/(?P<pk_2>\d+)/update/$', SnivelMasterUpdateView.as_view(), name='snivel_master_update'),    
    url(r'^snivel/(?P<pk>\d+)/delete/$', SnivelDeleteView.as_view(), name='snivel_delete'),
    url(r'^snivel/(?P<pk>\d+)/master/(?P<pk_2>\d+)/delete/$', SnivelMasterDeleteView.as_view(), name='snivel_master_delete'),    
   
]

src/magalytics/urls.py
from django.contrib.auth.decorators import permission_required
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

from command.views import (
	contact_create_modal,
)

from ship.views import (
					ShipCreateView,
					Gen_CertCreateView,
					Gen_CertListView,
					Gen_CertUpdateView,
					Assess_nameListView,
					Assess_nameUpdateView,
					Assess_nameCreateView,
					discrepancy_modal,
					issue_create_modal,

					
)

from profiles.views import (profile_create,
							teammember_create_modal,
							teammember_delete_modal
							)

from dashboard.views import (
				snivel_create_modal,
)

from administration.views import(
							designation_add_modal,
							designation_delete_modal
)
urlpatterns = [
	url(r'^ajax/hit_list/$', discrepancy_modal, name='ajax_hit_list'),
	url(r'^ajax/issue_list/$', issue_create_modal, name='ajax_issue_list'),
	url(r'^ajax/team_main/$', teammember_create_modal, name='ajax_team_main'),
	url(r'^ajax/team_delete/$', teammember_delete_modal, name='ajax_team_delete'),
	url(r'^ajax/snivel_create/$', snivel_create_modal, name='ajax_snivel_create'),
	url(r'^ajax/designation_delete/$', designation_delete_modal, name='ajax_designation_delete'),
	url(r'^ajax/designation_add/$', designation_add_modal, name='ajax_designation_add'),
	url(r'^ajax/contact_add/$', contact_create_modal, name='ajax_contact_add'),	
	url(r'', include('allauth.urls')),
	url(r'',  include('dashboard.urls', namespace='dashboard')),
	url(r'',  include('profiles.urls', namespace='profiles')),   	
	url(r'^admin/', admin.site.urls),
	url(r'^settings/$', staff_member_required(TemplateView.as_view(template_name='settings.html')), name='settings'),
	url(r'^settings/ship/$', ShipCreateView.as_view(), name='ship_create'),
	url(r'^settings/create_profile/$',profile_create, name='create_profile' ),
	url(r'^settings/generic_cert/$', Gen_CertListView.as_view(), name='gen_cert'),
	url(r'^settings/generic_cert/(?P<pk>\d+)/$', Gen_CertUpdateView.as_view(), name='gen_cert_update'),    
	url(r'^settings/generic_cert/create/$', Gen_CertCreateView.as_view(), name='gen_cert_create'),
	url(r'^settings/assessments/$', Assess_nameListView.as_view(), name='gen_assess'),
	url(r'^settings/assessments/(?P<pk>\d+)/$', Assess_nameUpdateView.as_view(), name='gen_assess_update'),    
	url(r'^settings/assessments/create/$', Assess_nameCreateView.as_view(), name='gen_assess_create'),
	url(r'', include('command.urls', namespace='command')),
	url(r'', include('ship.urls', namespace='ship')),
	url(r'', include('administration.urls', namespace='administration')),	
	]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/ship/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from .views import (
                ship_main,
                ShipDetailView,
                ShipUpdateView,
                Local_CertCreateView,
                Local_CertUpdateView,
                Loc_CertListView,
                HitDetailView,
                HitDeleteView,
                HitCreateView,
                HitUpdateView,
                HitListView,
                HitImageCreateView,
                HitImageUpdateView,
                HitImageDeleteView,
                assess_list_main,
                SpaceListView,
                SpaceCreateView,
                SpaceUpdateView,
                SpaceDeleteView,
                EquipmentListView,
                EquipmentCreateView,
                EquipmentUpdateView,
                EquipmentDeleteView,
                question,
                discrepancy_modal,
                QuestionCreateView,
                QuestionUpdateView,
                QuestionDeleteView,
                QuestionListView,
                SystemListView,
                SystemCreateView,
                issue_tracker,
                SystemUpdateView,
                SystemDeleteView,
                )

from .functions import (
    export_csv_hits,    
)

urlpatterns = [
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/$', ship_main, name='ship_main'),
    
    #Ship URls
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/$',
        ShipDetailView.as_view(), name='ship_detail'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/update/',
        ShipUpdateView.as_view(), name='ship_update'),

    #Class Desk URLs
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/$',
        issue_tracker, name='issue_tracker'),
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/systems/$', SystemListView, name='system_list'),
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/systems/create/$', SystemCreateView.as_view(), name='system_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/systems/(?P<pk>\d+)/update/$', SystemUpdateView.as_view(), name='system_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/systems/(?P<pk>\d+)/delete/$', SystemDeleteView.as_view(), name='system_delete'),

    #Cert URLs
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/certs/(?P<pk>\d+)/update/$',
        Local_CertUpdateView.as_view(), name='loc_cert_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/certs/create/$',
        Local_CertCreateView.as_view(), name='loc_cert_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/certs/$',
        Loc_CertListView, name='certs'),

    
    #Discrepancy URLs    
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/create/$',
        HitCreateView.as_view(), name='hit_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/$',
        HitListView, name='hits'),   
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/$',
        HitDetailView, name='hit_detail'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/images/$',
        HitImageCreateView.as_view(), name='hit_image'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/images/(?P<pk_1>\d+)/update/$',
        HitImageUpdateView.as_view(), name='hit_image_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/images/(?P<pk_1>\d+)/delete/$',
        HitImageDeleteView.as_view(), name='hit_image_delete'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/delete/$',
        HitDeleteView.as_view(), name='hit_delete'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/update/$',
        HitUpdateView.as_view(), name='hit_update'),
    
    #Assessment Urls
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/$',
        assess_list_main, name='assess_list_main'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/create/$',
        SpaceCreateView.as_view(), name='space_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk>\d+)/update/$',
        SpaceUpdateView.as_view(), name='space_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk>\d+)/delete/$',
        SpaceDeleteView.as_view(), name='space_delete'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/$',
        SpaceListView.as_view(), name='space_list'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/create/$',
        EquipmentCreateView.as_view(), name='equipment_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk>\d+)/update/$',
        EquipmentUpdateView.as_view(), name='equipment_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk>\d+)/delete/$',
        EquipmentDeleteView.as_view(), name='equipment_delete'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/$',
        EquipmentListView.as_view(), name='equipment_list'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk>\d+)/$',
        question , name='assessment'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk_2>\d+)/questions/$',
        QuestionListView.as_view(), name='question_list'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk_2>\d+)/questions/create/$',
        QuestionCreateView.as_view(), name='question_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk_2>\d+)/questions/(?P<pk>\d+)/update/$',
        QuestionUpdateView.as_view(), name='question_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk_2>\d+)/questions/(?P<pk>\d+)/delete/$',
        QuestionDeleteView.as_view(), name='question_delete'),

]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/dashboard/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models

from profiles.models import Team

User = settings.AUTH_USER_MODEL

class Events(models.Model):
    title = models.CharField(max_length=140)
    poc = models.ForeignKey(User)
    start = models.DateField()
    end = models.DateField()
    team = models.ForeignKey(Team, null=True, blank=True)
    description = models.TextField(max_length=None, null=True, blank=True)
    
    def __unicode__(self):
        return self.title
    
class Snivel(models.Model):
    member = models.ForeignKey(User)
    start = models.DateField()
    end = models.DateField()
    description = models.TextField(max_length=None, null=True, blank=True)
    
    def __unicode__(self):
        return self.member.username

src/profiles/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import signals
from django.contrib.auth.models import User

from command.models import Unit, Department, Division

# Create your models here.

P_User = settings.AUTH_USER_MODEL

E1 = "SA"
E2 = "SR"
E3 = "SN"
E4 = "PO3"
E5 = "PO2"
E6 = "PO1"
E7 = "CPO"
E8 = "SCPO"
E9 = "MCPO"

W2 = "CWO2"
W3 = "CWO3"
W4 = "CWO4"
W5 = "CWO5"

O1 = "ENS"
O2 = "LTJG"
O3 = "LT"
O4 = "LCDR"
O5 = "CDR"
O6 = "CAPT"
O7 = "RDML"
O8 = "RADM"
O9 = "VADM"
OO = "ADM"

RANK_CHOICES = (
    (E1, "SA"),
    (E2, "SR"),
    (E3, "SN"),
    (E4, "PO3"),
    (E5, "PO2"),
    (E6, "PO1"),
    (E7, "CPO"),
    (E8, "SCPO"),
    (E9, "MCPO"),
    (W2, "CWO2"),
    (W3, "CWO3"),
    (W4, "CWO4"),
    (W5, "CWO5"),
    (O1, "ENS"),
    (O2, "LTJG"),
    (O3, "LT"),
    (O4, "LCDR"),
    (O5, "CDR"),
    (O6, "CAPT"),
    (O7, "RDML"),
    (O8, "RADM"),
    (O9, "VADM"),
    (OO, "ADM"),
)

class Profile(models.Model):
    user = models.OneToOneField(User)
    unit = models.ForeignKey(Unit)
    department = models.ManyToManyField(Department, blank=True)
    division = models.ForeignKey(Division, null=True, blank=True, on_delete=models.SET_NULL)
    rank = models.CharField(max_length=4, choices=RANK_CHOICES, default= "PO2", null=True, blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+9999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(max_length=15, validators=[phone_regex], null=True, blank=True)
    check_in = models.DateField(null=True, blank=True)
    prd = models.DateField(null=True, blank=True)
    force_password_change = models.BooleanField(default=True)
    
    def __unicode__(self):
        return self.user.username
    
    class Meta:
        ordering = ['rank']
    
    def get_absolute_url(self):
        url = reverse("profile", kwargs={"username": self.username})
        return url


def password_change_signal(sender, instance, **kwargs):
    try:
        user = User.objects.get(username=instance.username)
        if not user.password == instance.password:
          profile = user.profile
          profile.force_password_change = False
          profile.save()
    except User.DoesNotExist:
        pass

signals.pre_save.connect(password_change_signal, sender=User, dispatch_uid='profiles.models')


ROLL_CHOICES = (
    ('Regular', 'Regular'),
    ('Staff', 'Staff'),
    ('TypeDesk', 'TypeDesk'),
)
class UserRole(models.Model):
    user = models.OneToOneField(User)
    role = models.CharField(max_length=120, default='Regular', choices=ROLL_CHOICES)
    
    def __unicode__(self):
        return self.role

class Designator(models.Model):
    code = models.CharField(max_length=50)
    name = models.CharField(max_length=10)
    description = models.CharField(max_length=100)
    
    def __unicode__(self):
        return self.name
    
class Designation(models.Model):    
    designator = models.ForeignKey(Designator)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return self.user.username

class Team(models.Model):
    title = models.CharField(max_length=60)
    team_lead = models.ForeignKey(User, null=True, blank=True)
    department = models.ForeignKey(Department)
    
    def __unicode__(self):
        return self.title    
    
class TeamMember(models.Model):
    title = models.ForeignKey(Team)
    member = models.ForeignKey(User)
    
    
    def __unicode__(self):
        return self.member.username
    

src/dashboard/forms.py
from django import forms
from django.db import models
from django.forms.widgets import SelectDateWidget
from .models import (
                Events,
                Snivel,
                )

class EventsForm(forms.ModelForm):
    class Meta:
        model = Events
        fields = [
            'title',
            'poc',
            'start',
            'end',
            'team',
            'description',
        ]
        widgets = { 'start': SelectDateWidget(years=range(2010, 2030)),
                'end': SelectDateWidget(years=range(2010, 2030)),
                   }

class SnivelForm(forms.ModelForm):
    class Meta:
        model = Snivel
        fields = [
            'start',
            'end',
            'description',
        ]
        widgets = { 'start': SelectDateWidget(years=range(2010, 2030)),
                'end': SelectDateWidget(years=range(2010, 2030)),
                   }

class SnivelMasterForm(forms.ModelForm):
    class Meta:
        model = Snivel
        fields = [
            'member',    
            'start',
            'end',
            'description',
        ]
        widgets = { 'start': SelectDateWidget(years=range(2010, 2030)),
                'end': SelectDateWidget(years=range(2010, 2030)),
                   }

src/templates/dashboard/events_confirm_delete.html
{% extends "base.html" %}
{% load staticfiles %}

{% block navbar %}

{% endblock %}


{% block content %}

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete this Event? "{{ object }}"</p>
    <input class='btn btn-danger' type="submit" value="Confirm" />
    <a class='btn btn-default' href="{% url 'dashboard:events_main' %}">Cancel</a>
</form>
    </div>

{% endblock %}

src/templates/dashboard/events_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block navbar %}
          <ul class="nav nav-sidebar">
            <li class="active"><a href="{% url 'dashboard:events_main' %}">Events Overview <span class="sr-only">(current)</span></a></li>
          </ul>
         
{% endblock %}
 

{% block content %}
<div class="page-header row">
  <div class="col-sm-6">
  <h1>{{ event.title }}</h1>
  </div>
    {% if perms.dashboard.update_events %}
    <div class="col-sm-3">
      <h4><a href="{% url 'dashboard:events_update' pk=event.pk %}">Update Events</h4></a>
    </div>
    {% endif %}  
    {% if perms.dashboard.delete_events %}
    <div class="col-sm-3">
      <h4><a href="{% url 'dashboard:events_delete' pk=event.pk %}">Delete Events</h4></a>
    </div>
    {% endif %}    
</div>
    
          <div class="row"><h3>POC: {{ event.poc }}</h3></div>
          <div class="row"><h3>Start Date: {{ event.start }}</h3></div>
          <div class="row"><h3>End Date: {{ event.end }}</h3></div>
          {% if event.team %}
          <div class="row"><h3>Team: {{ event.team }}</h3></div>
          {% else %}
          <div class="row"><h3>Team: No Team Assigned</h3></div>
          {% endif %}
          <div class="row"><h3>Description: <p>{{ event.description }}</p></h3></div>




{% endblock %}

src/templates/dashboard/events_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
    
    {% if title %}
    <h1 class='{% if title_align_center %}text-align-center{% endif %}'>{{ title }}</h1>
    {% endif %}
    
    <form  method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
	<div class="row">
	<div class='col-sm-6'>
	  {{ form.title|as_crispy_field }}</h4>
	</div>
	<div class='col-sm-6'>
		{{ form.team|as_crispy_field }}
	</div>
	</div>
	<div class="row">
	<div class='col-sm-6'>
	  {{ form.start|as_crispy_field }}</h4>
	</div>
	<div class='col-sm-6'>
		{{ form.end|as_crispy_field }}
	</div>
	<div class='col-sm-12'>
		<div class="row">
		{{ form.description|as_crispy_field }}
		</div>
	</div>
		{{ form.poc.as_hidden }}
    

    <input class='btn btn-default' type='submit' value='Submit' />
    <a class='btn btn-default' href="{% url 'dashboard:home' %}">Cancel</a>
       
</form>
</div>
</div>
{% endblock %}

src/templates/dashboard/events_main.html
{% extends "base.html" %}
{% load staticfiles %}
{% block navbar %}

         
{% endblock %}


{% block content %}
<div class="page-header row">
  <div class="col-sm-6">
  <h1>Event Manager</h1>
  </div>
    {% if perms.dashboard.add_events %}
	  <div class="col-sm-4 col-sm-offset-1">  
	  <a type="button" class="btn btn-md btn-default" href="{% url 'dashboard:events_create' %}">Add Event</a>
	  </div>
    {% endif %}
</div>
{% for event in event_list %}
  <div class="col-sm-4 col-md-4">
    <div class="thumbnail">
      <div class="caption">
<div class="row">
	<div class="col-sm-12">
		<h3 style='color: #90949c; text-align: center'>{{ event.title }}</h3>
	</div>
</div>
<div class="row">
	<div class="col-sm-4 col-sm-offset-1">
	<h4 style='color: #90949c'>Event POC:</h4>
	</div>
	<div class="col-sm-6">
		<h4 style='color: #90949c'>{{ event.poc.profile.rank }} {{ event.poc.first_name }} {{ event.poc.last_name }}</h4>
	</div>
</div>
<div class="row">
	<div class="col-sm-4 col-sm-offset-1">
	<h4 style='color: #90949c'>Team:</h4>
	</div>
	<div class="col-sm-6">
		<h4 style='color: #90949c'>{{ event.team }}</h4>
	</div>	
</div>
<div class="row">
  <div class="col-sm-6 col-sm-offset-2">
	<hr/>
  </div>	
</div>

<div class="row">
	<div class="col-sm-4 col-sm-offset-1">
	<h4 style='color: #90949c'>Start Date:</h4>
	</div>
	<div class="col-sm-6">
		<h4 style='color: #90949c'>{{ event.start }}</h4>
	</div>
</div>
<div class="row">
	<div class="col-sm-4 col-sm-offset-1">
	<h4 style='color: #90949c'>End Date:</h4>
	</div>
	<div class="col-sm-6">
		<h4 style='color: #90949c'>{{ event.end }}</h4>
	</div>
</div>
</br>
{% if event.team %} 
{% endif %}
</br>
<!--Filter Drop Down	-->
<div class="row">
  <div class="col-sm-12">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true"> 
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="{{ event }}">
            <h4 class="panel-title">
              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#{{ event.id }}" aria-expanded="false" aria-controls="{{ event.id }}">
                Description
              </a>
            </h4>
          </div>             
          <div id="{{ event.id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="{{ event }}">
			<div class="panel-body">
			  <p>{{ event.description }}</p>
			</div>
		  </div>
		</div>
		<div class="panel panel-default">
		  <div class="panel-heading" role="tab" id="{{ event }}2">
			<h4 class="panel-title">
			  <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#{{ event.id }}2" aria-expanded="false" aria-controls="{{ event.id }}2">
				{{ event.team.title }} Member Conflicts
			  </a>
			</h4>
		  </div>
		  <div id="{{ event.id }}2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
			<div class="panel-body">
          <!--Members-->
			  {% for member in event.team.teammember_set.all %}
				<div class="col-sm-12">
					{% for snivel in member.member.snivel_set.all %}
					  {% if snivel.start <= event.start and snivel.end >= event.start %}
						<h5 style='color: #90949c'><a href="{% url 'profiles:snivel_master' pk=member.member.profile.pk %}">{{ member.member.profile.rank }} {{ member.member.first_name }} {{ member.member.last_name }}</a>&nbsp;&nbsp;{{ snivel.description|truncatechars:30 }}</h5>
					  {% elif snivel.start <= event.end and snivel.end >= event.end %}
						<h5 style='color: #90949c'><a href="{% url 'profiles:snivel_master' pk=member.member.profile.pk %}">{{ member.member.profile.rank }} {{ member.member.first_name }} {{ member.member.last_name }}</a>&nbsp;&nbsp;{{ snivel.description|truncatechars:30 }}</h5>
						{% endif %}
					  {% endfor %}
				  </div>		
			  {% endfor %}			  
			</div>
		  </div>
		</div>		
	</div>
  </div>
</div>
</br>
<div class="row">
  <div class="col-sm-4 col-sm-offset-1">  
  <a type="button" class="btn btn-md btn-primary" href="{% url 'dashboard:events_update' pk=event.pk %}">Edit Event</a>
  </div>
  {% if perms.profiles.delete_team %}
  <div class="col-sm-4 col-sm-offset-1">  
    <a type="button" class="btn btn-md btn-danger" href="{% url 'dashboard:events_delete' pk=event.pk %}">Delete Event</a>
  </div>
  {% endif %}
</div>
      </div>
    </div>
  </div>

{% endfor %}

{% endblock %}