src/command/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from .views import (
					UnitCreateView,
					UnitUpdateView,
					UnitDetailView,
					UnitListView,
					UnitAssetUpdateView,
					DeptCreateView,
					DeptUpdateView,
					DeptDetailView,
					DeptListView,
					DivCreateView,
					DivUpdateView,
					DivDetail,
					DivListView,
					contact_list,
					ContactUpdateView,
					ContactDeleteView,
					Instruction_list,
					InstructionCreateView,
					InstructionUpdateView,
					InstructionDeleteView,
					)


urlpatterns = [
	url(r'^settings/command/(?P<unit_slug>[-\w]+)/(?P<dept_slug>[-\w]+)/(?P<div_slug>[-\w]+)/update/', DivUpdateView.as_view(), name='div_update'),        
	url(r'^settings/command/(?P<unit_slug>[-\w]+)/(?P<dept_slug>[-\w]+)/create/$', DivCreateView.as_view(), name='div_create'),	
	url(r'^settings/command/(?P<unit_slug>[-\w]+)/(?P<dept_slug>[-\w]+)/update/', DeptUpdateView.as_view(), name='dept_update'),
	url(r'^settings/command/(?P<unit_slug>[-\w]+)/create/$', DeptCreateView.as_view(), name='dept_create'),		
	url(r'^settings/command/(?P<unit_slug>[-\w]+)/update/$', UnitUpdateView.as_view(), name='unit_update'),
	url(r'^settings/command/(?P<unit_slug>[-\w]+)/assets/$', UnitAssetUpdateView.as_view(), name='asset_update'),	
	url(r'^settings/command/(?P<unit_slug>[-\w]+)/(?P<dept_slug>[-\w]+)/$', DivListView.as_view(), name='div_list'),                     
	url(r'^settings/command/create/$', UnitCreateView.as_view(), name='unit_create'),
	url(r'^settings/command/(?P<unit_slug>[-\w]+)/$', DeptListView.as_view(), name='dept_list'),
	url(r'^settings/command/$', UnitListView.as_view(), name='unit_list'),
	url(r'^contact/$', contact_list, name='contact_list'),
	url(r'^contact/(?P<pk>\d+)/update/$', ContactUpdateView.as_view(), name='contact_update'),
	url(r'^contact/(?P<pk>\d+)/delete/$', ContactDeleteView.as_view(), name='contact_delete'),
	url(r'^instruction/$', Instruction_list, name='instruction_list'),
	url(r'^instruction/create/$', InstructionCreateView.as_view(), name='instruction_create'),
	url(r'^instruction/(?P<pk>\d+)/update/$', InstructionUpdateView.as_view(), name='instruction_update'),
	url(r'^instruction/(?P<pk>\d+)/delete/$', InstructionDeleteView.as_view(), name='instruction_delete'),	


]

if settings.DEBUG:
	urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/magalytics/urls.py
from django.contrib.auth.decorators import permission_required
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

from command.views import (
	contact_create_modal,
)

from ship.views import (
					ShipCreateView,
					Gen_CertCreateView,
					Gen_CertListView,
					Gen_CertUpdateView,
					Assess_nameListView,
					Assess_nameUpdateView,
					Assess_nameCreateView,
					discrepancy_modal,
					issue_create_modal,

					
)

from profiles.views import (profile_create,
							teammember_create_modal,
							teammember_delete_modal
							)

from dashboard.views import (
				snivel_create_modal,
)

from administration.views import(
							designation_add_modal,
							designation_delete_modal
)
urlpatterns = [
	url(r'^ajax/hit_list/$', discrepancy_modal, name='ajax_hit_list'),
	url(r'^ajax/issue_list/$', issue_create_modal, name='ajax_issue_list'),
	url(r'^ajax/team_main/$', teammember_create_modal, name='ajax_team_main'),
	url(r'^ajax/team_delete/$', teammember_delete_modal, name='ajax_team_delete'),
	url(r'^ajax/snivel_create/$', snivel_create_modal, name='ajax_snivel_create'),
	url(r'^ajax/designation_delete/$', designation_delete_modal, name='ajax_designation_delete'),
	url(r'^ajax/designation_add/$', designation_add_modal, name='ajax_designation_add'),
	url(r'^ajax/contact_add/$', contact_create_modal, name='ajax_contact_add'),	
	url(r'', include('allauth.urls')),
	url(r'',  include('dashboard.urls', namespace='dashboard')),
	url(r'',  include('profiles.urls', namespace='profiles')),   	
	url(r'^admin/', admin.site.urls),
	url(r'^settings/$', staff_member_required(TemplateView.as_view(template_name='settings.html')), name='settings'),
	url(r'^settings/ship/$', ShipCreateView.as_view(), name='ship_create'),
	url(r'^settings/create_profile/$',profile_create, name='create_profile' ),
	url(r'^settings/generic_cert/$', Gen_CertListView.as_view(), name='gen_cert'),
	url(r'^settings/generic_cert/(?P<pk>\d+)/$', Gen_CertUpdateView.as_view(), name='gen_cert_update'),    
	url(r'^settings/generic_cert/create/$', Gen_CertCreateView.as_view(), name='gen_cert_create'),
	url(r'^settings/assessments/$', Assess_nameListView.as_view(), name='gen_assess'),
	url(r'^settings/assessments/(?P<pk>\d+)/$', Assess_nameUpdateView.as_view(), name='gen_assess_update'),    
	url(r'^settings/assessments/create/$', Assess_nameCreateView.as_view(), name='gen_assess_create'),
	url(r'', include('command.urls', namespace='command')),
	url(r'', include('ship.urls', namespace='ship')),
	url(r'', include('administration.urls', namespace='administration')),	
	]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/ship/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from .views import (
                ship_main,
                ShipDetailView,
                ShipUpdateView,
                Local_CertCreateView,
                Local_CertUpdateView,
                Loc_CertListView,
                HitDetailView,
                HitDeleteView,
                HitCreateView,
                HitUpdateView,
                HitListView,
                HitImageCreateView,
                HitImageUpdateView,
                HitImageDeleteView,
                assess_list_main,
                SpaceListView,
                SpaceCreateView,
                SpaceUpdateView,
                SpaceDeleteView,
                EquipmentListView,
                EquipmentCreateView,
                EquipmentUpdateView,
                EquipmentDeleteView,
                question,
                discrepancy_modal,
                QuestionCreateView,
                QuestionUpdateView,
                QuestionDeleteView,
                QuestionListView,
                SystemListView,
                SystemCreateView,
                issue_tracker,
                SystemUpdateView,
                SystemDeleteView,
                )

from .functions import (
    export_csv_hits,    
)

urlpatterns = [
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/$', ship_main, name='ship_main'),
    
    #Ship URls
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/$',
        ShipDetailView.as_view(), name='ship_detail'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/update/',
        ShipUpdateView.as_view(), name='ship_update'),

    #Class Desk URLs
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/$',
        issue_tracker, name='issue_tracker'),
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/systems/$', SystemListView, name='system_list'),
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/systems/create/$', SystemCreateView.as_view(), name='system_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/systems/(?P<pk>\d+)/update/$', SystemUpdateView.as_view(), name='system_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/systems/(?P<pk>\d+)/delete/$', SystemDeleteView.as_view(), name='system_delete'),

    #Cert URLs
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/certs/(?P<pk>\d+)/update/$',
        Local_CertUpdateView.as_view(), name='loc_cert_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/certs/create/$',
        Local_CertCreateView.as_view(), name='loc_cert_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/certs/$',
        Loc_CertListView, name='certs'),

    
    #Discrepancy URLs    
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/create/$',
        HitCreateView.as_view(), name='hit_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/$',
        HitListView, name='hits'),   
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/$',
        HitDetailView, name='hit_detail'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/images/$',
        HitImageCreateView.as_view(), name='hit_image'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/images/(?P<pk_1>\d+)/update/$',
        HitImageUpdateView.as_view(), name='hit_image_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/images/(?P<pk_1>\d+)/delete/$',
        HitImageDeleteView.as_view(), name='hit_image_delete'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/delete/$',
        HitDeleteView.as_view(), name='hit_delete'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/update/$',
        HitUpdateView.as_view(), name='hit_update'),
    
    #Assessment Urls
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/$',
        assess_list_main, name='assess_list_main'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/create/$',
        SpaceCreateView.as_view(), name='space_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk>\d+)/update/$',
        SpaceUpdateView.as_view(), name='space_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk>\d+)/delete/$',
        SpaceDeleteView.as_view(), name='space_delete'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/$',
        SpaceListView.as_view(), name='space_list'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/create/$',
        EquipmentCreateView.as_view(), name='equipment_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk>\d+)/update/$',
        EquipmentUpdateView.as_view(), name='equipment_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk>\d+)/delete/$',
        EquipmentDeleteView.as_view(), name='equipment_delete'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/$',
        EquipmentListView.as_view(), name='equipment_list'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk>\d+)/$',
        question , name='assessment'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk_2>\d+)/questions/$',
        QuestionListView.as_view(), name='question_list'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk_2>\d+)/questions/create/$',
        QuestionCreateView.as_view(), name='question_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk_2>\d+)/questions/(?P<pk>\d+)/update/$',
        QuestionUpdateView.as_view(), name='question_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk_2>\d+)/questions/(?P<pk>\d+)/delete/$',
        QuestionDeleteView.as_view(), name='question_delete'),

]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/command/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.db import models
from django.core.validators import RegexValidator
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from ship.validators import validate_file_extension

class Asset_Type(models.Model):
	name = models.CharField(max_length=50)
	
	def __unicode__(self):
		return str(self.name)

class Unit(models.Model):
	name = models.CharField(max_length=50)
	unit_slug = models.SlugField(unique=True)
	uic = models.IntegerField()
	assets = models.ManyToManyField("Unit", blank=True)
	asset_type = models.ManyToManyField(Asset_Type, blank=True)

	
	class Meta:
		ordering = ['uic']

	def __unicode__(self):
		return str(self.name)

def create_unit_slug(instance, new_slug=None):
	unit_slug = slugify(instance.name)
	if new_slug is not None:
		unit_slug = new_slug
	qs = Unit.objects.filter(unit_slug=unit_slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(unit_slug, qs.first().id)
		return create_unit_slug(instance, new_slug=new_slug)
	return unit_slug

def pre_save_receiver(sender, instance, *args, **kwargs):
	if not instance.unit_slug:
		instance.unit_slug = create_unit_slug(instance)

class Department(models.Model):
	name = models.CharField(max_length=50)
	dept_slug = models.SlugField(unique=True)
	unit = models.ForeignKey(Unit, blank=True, null=True)
	asset_type_manager = models.ManyToManyField(Asset_Type, blank=True)
	
	class Meta:
		ordering = ['name']

	def __unicode__(self):
		return str(self.name)

def create_dept_slug(instance, new_slug=None):
	dept_slug = slugify(instance.name)
	if new_slug is not None:
		dept_slug = new_slug
	qs = Department.objects.filter(dept_slug=dept_slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(dept_slug, qs.first().id)
		return create_dept_slug(instance, new_slug=new_slug)
	return dept_slug

def pre_save_dept_receiver(sender, instance, *args, **kwargs):
	if not instance.dept_slug:
		instance.dept_slug = create_dept_slug(instance)

class Division(models.Model):
    name = models.CharField(max_length=50)
    div_slug = models.SlugField(unique=True)
    unit = models.ForeignKey(Unit, blank=True, null=True)
    department = models.ForeignKey(Department, blank=True, null=True)

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return str(self.name)

def create_div_slug(instance, new_slug=None):
	div_slug = slugify(instance.name)
	if new_slug is not None:
		div_slug = new_slug
	qs = Division.objects.filter(div_slug=div_slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(div_slug, qs.first().id)
		return create_div_slug(instance, new_slug=new_slug)
	return div_slug

def pre_save_div_receiver(sender, instance, *args, **kwargs):
	if not instance.div_slug:
		instance.div_slug = create_div_slug(instance)

class Contact(models.Model):
	name = models.CharField(max_length=140)
	phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+9999999999'. Up to 15 digits allowed.")
	phone_number = models.CharField(max_length=15, validators=[phone_regex])
	unit = models.ForeignKey(Unit)
	
	def __unicode__(self):
		return str(self.name)

def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)
	
class Instruction(models.Model):
	name = models.CharField(max_length=255)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	document = models.FileField(upload_to=upload_location, validators=[validate_file_extension])
	unit = models.ForeignKey(Unit, blank=True, null=True)
	
	def __unicode__(self):
		return str(self.name)

pre_save.connect(pre_save_receiver, sender=Unit)
pre_save.connect(pre_save_dept_receiver, sender=Department)
pre_save.connect(pre_save_div_receiver, sender=Division)

src/command/forms.py
from django import forms
from django.db import models
from .models import Unit, Department, Division, Contact, Instruction


class UnitForm(forms.ModelForm):
    class Meta:
        model = Unit
        fields = [
            'name',
            'uic',
            'assets',
            'asset_type',
        ]        

class UnitAssetForm(forms.ModelForm):
    class Meta:
        model = Unit
        fields = [
            'assets',
        ]  

class DeptForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(DeptForm, self).__init__(*args, **kwargs)
        self.fields['unit'].empty_label=None      
    class Meta:
        model = Department
        fields = [
            'name',
            'unit',
        ] 

class DivForm(forms.ModelForm):
    class Meta:
        model = Division
        fields = [
            'name',
            'unit',
            'department',
            ]
        
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = [
            'name',
            'phone_number',
            'unit',
        ]
        
class InstructionForm(forms.ModelForm):
    class Meta:
        model = Instruction
        fields = [
            'user',
            'name',
            'document',
            'unit',
        ]

src/templates/command/contact_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block navbar %}

{% endblock %}

{% block script %}

<script>
    $(document).ready(function() 
        { 
            $("#domainsTable").tablesorter(); 
        } 
    );
    </script>


{% endblock %}

{% block content %}

<div class="page-header row">
  <div class="col-sm-6 col-sm-offset-3">
  <h1>Contact List <small>  {{ unit.name }}</small></h1>
  </div>     
</div>

<div class="row">
  
  
    <div class="col-sm-3">
	<form method='GET' action=''>
		<div class='input-group'>
			<input class='form-control' type='text' name='q' placeholder='Search' value='{{ request.GET.q }}'/>
			<span class='input-group-btn'>
			<input class='btn btn-default' type='submit' value='Search' />
			</span>
		</div>
	</form>
	</div>
     {% if perms.command.add_contact %}	
    <div class='col-sm-3'>
        <button type="button" class="btn btn-success" data-toggle="modal" data-target=".bs-example-modal-lg">Add Contact</button>
         <div class='col-sm-10'>
           <div class="modal fade bs-example-modal-lg" id="EventModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
             <div class="modal-dialog modal-lg">
               <div class="modal-content">
			<form id ='sendForm' method='POST' action='{% url "ajax_contact_add"  %}' enctype='multipart/form-data'>{% csrf_token %}
			  <p id='modalMessage'></p>
                <div class="row">
                    <div class='col-sm-4 col-sm-offset-2'>
                        {{ form.name|as_crispy_field }}
                        </div>
                    <div class='col-sm-4'>
                        {{ form.phone_number|as_crispy_field }}
                    </div>    
                </div>        
                        {{ form.unit.as_hidden }}
					<div class='row'>
						<div class='col-sm-3 col-sm-offset-3'>
						<input type='submit' class='btn btn-default' value='Save' id='sendEventForm' />
						</div>
					</div>
              </form>
              </div>	
           </div>
         </div>
       </div>
    </div>
{% endif %}    
</div>

<hr/>

  <div class="table">
	<table id="domainsTable" class="table tablesorter"> 
	  <thead>       
		<tr>
		<th>Name</th>		
		<th>Phone Number</th>
        {% if perms.command.change_contact %}
		<th></th>
        {% endif %}
        {% if perms.command.delete_contact %}
        <th></th>
        {% endif %}
		</tr>
	  </thead>        
{% for contact in contact_list %}        
      <tr>
		<td>{{ contact.name }}</td>
        <td><a href="tel:+1{{ contact.phone_number }}">{{ contact.phone_number }}</a></td>
        {% if perms.command.change_contact %}
		<td><a type="button" class="btn btn-primary" href="{% url 'command:contact_update' pk=contact.pk %}"><span class="fa fa-pencil-square"></span> Edit</a></td>
		{% endif %}
        {% if perms.command.delete_contact %}
        <td><a type="button" class="btn btn-default" href="{% url 'command:contact_delete' pk=contact.pk %}"><span class="fa fa-minus-square"></span> Delete</a></td>
        {% endif %}
      </tr>
{% endfor %}       

<script>
$(document).ready(function(){           
	$("#sendEventForm").click(function(e){
		e.preventDefault()    
		var mForm = $("#sendForm").serialize();
		$.ajax({
			type: "POST",
			url: "{% url 'ajax_contact_add'  %}",
			data: mForm,              
			success: function(data){
				console.log(data)
				$("#modalMessage").html("<p>This was Successful</p>")
				   $("#EventModal").modal("hide")
				  location.reload()
			},
			error: function(data){ 
				var obj = data.responseJSON
				console.log(obj)
				$("#modalMessage").html("<p>Please Fill out All Fields!</p>");
			}
		});
			
	});
  });  

</script>



{% endblock %}

src/templates/command/instruction_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block navbar %}

{% endblock %}

{% block script %}

<script>
    $(document).ready(function() 
        { 
            $("#domainsTable").tablesorter(); 
        } 
    );
    </script>


{% endblock %}

{% block content %}

<div class="page-header row">
  <div class="col-sm-6 col-sm-offset-3">
  <h1>Command Instructions <small>  {{ unit.name }}</small></h1>
  </div>
</div>

<div class="row">
  
  
    <div class="col-sm-3">
	<form method='GET' action=''>
		<div class='input-group'>
			<input class='form-control' type='text' name='q' placeholder='Search' value='{{ request.GET.q }}'/>
			<span class='input-group-btn'>
			<input class='btn btn-default' type='submit' value='Search' />
			</span>
		</div>
	</form>
	</div>
    {% if perms.command.add_instruction %}
    <div class="row">
      <div class="col-sm-3">  
      <a type="button" class="btn btn-md btn-default" href="{% url 'command:instruction_create' %}">Add Instruction</a>
      </div>
    </div>
    {% endif %}      
</div>

<hr/>

  <div class="table">
	<table id="domainsTable" class="table tablesorter"> 
	  <thead>       
		<tr>
		<th>Name</th>
        {% if perms.command.change_instruction %}
		<th></th>
        {% endif %}
        {% if perms.command.delete_instruction %}
		<th></th>
        {% endif %}
        <th>Last Updated By</th>
		</tr>
	  </thead>        
{% for instruction in instruction_list %}        
      <tr>
		<td><a target="_blank" href="{{ instruction.document.url }}">{{ instruction.name }}</a></td>
        {% if perms.command.change_instruction %}
		<td><a type="button" class="btn btn-primary" href="{% url 'command:instruction_update' pk=instruction.pk %}"><span class="fa fa-pencil-square"></span> Edit</a></td>
		{% endif %}
        {% if perms.command.delete_instruction %}
        <td><a type="button" class="btn btn-default" href="{% url 'command:instruction_delete' pk=instruction.pk %}"><span class="fa fa-minus-square"></span> Delete</a></td>
        {% endif %}
        <td>{{ instruction.user.profile.rank }} {{ instruction.user.first_name }} {{ instruction.user.last_name }}</td>
      </tr>
{% endfor %}       




{% endblock %}

src/templates/command/unit_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block navbar %}
          <ul class="nav nav-sidebar">
            <li class="active"><a href="{% url 'settings' %}">Settings <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Reports</a></li>
          </ul>
{% endblock %}

{% block script %}

<script>
    $(document).ready(function() 
        { 
            $("#domainsTable").tablesorter(); 
        } 
    );
    </script>


{% endblock %}

{% block content %}
      <h1 class="page-header">Command List</h1>
<div class="row">
    <div class="col-sm-9">
    </div>    
    <div class="col-sm-3">
      <a type="button" class="btn btn-success" href="{% url 'command:unit_create' %}"><span class="fa fa-check-square"></span> Add Command</a>
    </div>
</div>
<hr/>

  <div class="table">
	<table id="domainsTable" class="table tablesorter"> 
	  <thead>       
		<tr>
		  <th>Name</th>
		  <th>UIC</th>
		  <th>Command Type</th>
          <th>Assets</th>
		</tr>
	  </thead>        
{% for object in object_list %}        
      <tr>
        <td><a href="{% url 'command:dept_list' unit_slug=object.unit_slug %}" title="Permanent Link to {{ object.name}}"> {{ object.name }}</a></td>
        <td>{{ object.uic }}</td>
        <td>
          {% for asset_type in object.asset_type.all %}
          {{ asset_type.name }}
          {% endfor %}
        </td>
        <td>{{ object.assets.count }}</td>

      </tr>
{% endfor %}       








{% endblock %}