src/magalytics/urls.py
from django.contrib.auth.decorators import permission_required
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

from command.views import (
	contact_create_modal,
)

from ship.views import (
					ShipCreateView,
					Gen_CertCreateView,
					Gen_CertListView,
					Gen_CertUpdateView,
					Assess_nameListView,
					Assess_nameUpdateView,
					Assess_nameCreateView,
					discrepancy_modal,
					issue_create_modal,

					
)

from profiles.views import (profile_create,
							teammember_create_modal,
							teammember_delete_modal
							)

from dashboard.views import (
				snivel_create_modal,
)

from administration.views import(
							designation_add_modal,
							designation_delete_modal
)
urlpatterns = [
	url(r'^ajax/hit_list/$', discrepancy_modal, name='ajax_hit_list'),
	url(r'^ajax/issue_list/$', issue_create_modal, name='ajax_issue_list'),
	url(r'^ajax/team_main/$', teammember_create_modal, name='ajax_team_main'),
	url(r'^ajax/team_delete/$', teammember_delete_modal, name='ajax_team_delete'),
	url(r'^ajax/snivel_create/$', snivel_create_modal, name='ajax_snivel_create'),
	url(r'^ajax/designation_delete/$', designation_delete_modal, name='ajax_designation_delete'),
	url(r'^ajax/designation_add/$', designation_add_modal, name='ajax_designation_add'),
	url(r'^ajax/contact_add/$', contact_create_modal, name='ajax_contact_add'),	
	url(r'', include('allauth.urls')),
	url(r'',  include('dashboard.urls', namespace='dashboard')),
	url(r'',  include('profiles.urls', namespace='profiles')),   	
	url(r'^admin/', admin.site.urls),
	url(r'^settings/$', staff_member_required(TemplateView.as_view(template_name='settings.html')), name='settings'),
	url(r'^settings/ship/$', ShipCreateView.as_view(), name='ship_create'),
	url(r'^settings/create_profile/$',profile_create, name='create_profile' ),
	url(r'^settings/generic_cert/$', Gen_CertListView.as_view(), name='gen_cert'),
	url(r'^settings/generic_cert/(?P<pk>\d+)/$', Gen_CertUpdateView.as_view(), name='gen_cert_update'),    
	url(r'^settings/generic_cert/create/$', Gen_CertCreateView.as_view(), name='gen_cert_create'),
	url(r'^settings/assessments/$', Assess_nameListView.as_view(), name='gen_assess'),
	url(r'^settings/assessments/(?P<pk>\d+)/$', Assess_nameUpdateView.as_view(), name='gen_assess_update'),    
	url(r'^settings/assessments/create/$', Assess_nameCreateView.as_view(), name='gen_assess_create'),
	url(r'', include('command.urls', namespace='command')),
	url(r'', include('ship.urls', namespace='ship')),
	url(r'', include('administration.urls', namespace='administration')),	
	]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

from .views import (
                    team_main,
                    TeamCreateView,
                    TeamUpdateView,
                    TeamDeleteView,
                    profile_main,
                    ProfileUpdateView,
                    TeamMemberCreateView,
                    )

from dashboard.views import (
                    snivel_master,
)


urlpatterns = [
    url(r'^profile/(?P<pk>\d+)/$', profile_main, name='profile_main'),
    url(r'^profile/(?P<pk>\d+)/update/$', ProfileUpdateView.as_view(), name='profile_update'),
    url(r'^team_manager/$', team_main, name='team_main'),
    url(r'^team_manager/create/$', TeamCreateView, name='team_create'),
    url(r'^team_manager/(?P<pk>\d+)/change/$', TeamMemberCreateView, name='member_change'),     
    url(r'^team_manager/(?P<pk>\d+)/update/$', TeamUpdateView.as_view(), name='team_update'),
    url(r'^team_manager/(?P<pk>\d+)/delete/$', TeamDeleteView.as_view(), name='team_delete'),
    url(r'^team_manager/snivel/(?P<pk>\d+)/$', snivel_master, name='snivel_master'),

]

src/ship/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from .views import (
                ship_main,
                ShipDetailView,
                ShipUpdateView,
                Local_CertCreateView,
                Local_CertUpdateView,
                Loc_CertListView,
                HitDetailView,
                HitDeleteView,
                HitCreateView,
                HitUpdateView,
                HitListView,
                HitImageCreateView,
                HitImageUpdateView,
                HitImageDeleteView,
                assess_list_main,
                SpaceListView,
                SpaceCreateView,
                SpaceUpdateView,
                SpaceDeleteView,
                EquipmentListView,
                EquipmentCreateView,
                EquipmentUpdateView,
                EquipmentDeleteView,
                question,
                discrepancy_modal,
                QuestionCreateView,
                QuestionUpdateView,
                QuestionDeleteView,
                QuestionListView,
                SystemListView,
                SystemCreateView,
                issue_tracker,
                SystemUpdateView,
                SystemDeleteView,
                )

from .functions import (
    export_csv_hits,    
)

urlpatterns = [
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/$', ship_main, name='ship_main'),
    
    #Ship URls
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/$',
        ShipDetailView.as_view(), name='ship_detail'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/update/',
        ShipUpdateView.as_view(), name='ship_update'),

    #Class Desk URLs
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/$',
        issue_tracker, name='issue_tracker'),
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/systems/$', SystemListView, name='system_list'),
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/systems/create/$', SystemCreateView.as_view(), name='system_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/systems/(?P<pk>\d+)/update/$', SystemUpdateView.as_view(), name='system_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/class_tracker/systems/(?P<pk>\d+)/delete/$', SystemDeleteView.as_view(), name='system_delete'),

    #Cert URLs
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/certs/(?P<pk>\d+)/update/$',
        Local_CertUpdateView.as_view(), name='loc_cert_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/certs/create/$',
        Local_CertCreateView.as_view(), name='loc_cert_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/certs/$',
        Loc_CertListView, name='certs'),

    
    #Discrepancy URLs    
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/create/$',
        HitCreateView.as_view(), name='hit_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/$',
        HitListView, name='hits'),   
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/$',
        HitDetailView, name='hit_detail'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/images/$',
        HitImageCreateView.as_view(), name='hit_image'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/images/(?P<pk_1>\d+)/update/$',
        HitImageUpdateView.as_view(), name='hit_image_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/images/(?P<pk_1>\d+)/delete/$',
        HitImageDeleteView.as_view(), name='hit_image_delete'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/delete/$',
        HitDeleteView.as_view(), name='hit_delete'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/hits/(?P<pk>\d+)/update/$',
        HitUpdateView.as_view(), name='hit_update'),
    
    #Assessment Urls
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/$',
        assess_list_main, name='assess_list_main'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/create/$',
        SpaceCreateView.as_view(), name='space_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk>\d+)/update/$',
        SpaceUpdateView.as_view(), name='space_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk>\d+)/delete/$',
        SpaceDeleteView.as_view(), name='space_delete'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/$',
        SpaceListView.as_view(), name='space_list'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/create/$',
        EquipmentCreateView.as_view(), name='equipment_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk>\d+)/update/$',
        EquipmentUpdateView.as_view(), name='equipment_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk>\d+)/delete/$',
        EquipmentDeleteView.as_view(), name='equipment_delete'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/$',
        EquipmentListView.as_view(), name='equipment_list'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk>\d+)/$',
        question , name='assessment'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk_2>\d+)/questions/$',
        QuestionListView.as_view(), name='question_list'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk_2>\d+)/questions/create/$',
        QuestionCreateView.as_view(), name='question_create'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk_2>\d+)/questions/(?P<pk>\d+)/update/$',
        QuestionUpdateView.as_view(), name='question_update'),
    url(r'^(?P<ship_main_slug>[-\w]+)/ships/(?P<ship_slug>[-\w]+)/assessments/(?P<assess_slug>[-\w]+)/space/(?P<pk_1>\d+)/equipment/(?P<pk_2>\d+)/questions/(?P<pk>\d+)/delete/$',
        QuestionDeleteView.as_view(), name='question_delete'),

]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import signals
from django.contrib.auth.models import User

from command.models import Unit, Department, Division

# Create your models here.

P_User = settings.AUTH_USER_MODEL

E1 = "SA"
E2 = "SR"
E3 = "SN"
E4 = "PO3"
E5 = "PO2"
E6 = "PO1"
E7 = "CPO"
E8 = "SCPO"
E9 = "MCPO"

W2 = "CWO2"
W3 = "CWO3"
W4 = "CWO4"
W5 = "CWO5"

O1 = "ENS"
O2 = "LTJG"
O3 = "LT"
O4 = "LCDR"
O5 = "CDR"
O6 = "CAPT"
O7 = "RDML"
O8 = "RADM"
O9 = "VADM"
OO = "ADM"

RANK_CHOICES = (
    (E1, "SA"),
    (E2, "SR"),
    (E3, "SN"),
    (E4, "PO3"),
    (E5, "PO2"),
    (E6, "PO1"),
    (E7, "CPO"),
    (E8, "SCPO"),
    (E9, "MCPO"),
    (W2, "CWO2"),
    (W3, "CWO3"),
    (W4, "CWO4"),
    (W5, "CWO5"),
    (O1, "ENS"),
    (O2, "LTJG"),
    (O3, "LT"),
    (O4, "LCDR"),
    (O5, "CDR"),
    (O6, "CAPT"),
    (O7, "RDML"),
    (O8, "RADM"),
    (O9, "VADM"),
    (OO, "ADM"),
)

class Profile(models.Model):
    user = models.OneToOneField(User)
    unit = models.ForeignKey(Unit)
    department = models.ManyToManyField(Department, blank=True)
    division = models.ForeignKey(Division, null=True, blank=True, on_delete=models.SET_NULL)
    rank = models.CharField(max_length=4, choices=RANK_CHOICES, default= "PO2", null=True, blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+9999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(max_length=15, validators=[phone_regex], null=True, blank=True)
    check_in = models.DateField(null=True, blank=True)
    prd = models.DateField(null=True, blank=True)
    force_password_change = models.BooleanField(default=True)
    
    def __unicode__(self):
        return self.user.username
    
    class Meta:
        ordering = ['rank']
    
    def get_absolute_url(self):
        url = reverse("profile", kwargs={"username": self.username})
        return url


def password_change_signal(sender, instance, **kwargs):
    try:
        user = User.objects.get(username=instance.username)
        if not user.password == instance.password:
          profile = user.profile
          profile.force_password_change = False
          profile.save()
    except User.DoesNotExist:
        pass

signals.pre_save.connect(password_change_signal, sender=User, dispatch_uid='profiles.models')


ROLL_CHOICES = (
    ('Regular', 'Regular'),
    ('Staff', 'Staff'),
    ('TypeDesk', 'TypeDesk'),
)
class UserRole(models.Model):
    user = models.OneToOneField(User)
    role = models.CharField(max_length=120, default='Regular', choices=ROLL_CHOICES)
    
    def __unicode__(self):
        return self.role

class Designator(models.Model):
    code = models.CharField(max_length=50)
    name = models.CharField(max_length=10)
    description = models.CharField(max_length=100)
    
    def __unicode__(self):
        return self.name
    
class Designation(models.Model):    
    designator = models.ForeignKey(Designator)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return self.user.username

class Team(models.Model):
    title = models.CharField(max_length=60)
    team_lead = models.ForeignKey(User, null=True, blank=True)
    department = models.ForeignKey(Department)
    
    def __unicode__(self):
        return self.title    
    
class TeamMember(models.Model):
    title = models.ForeignKey(Team)
    member = models.ForeignKey(User)
    
    
    def __unicode__(self):
        return self.member.username
    

src/profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db import models
from django.forms.widgets import SelectDateWidget
from django.conf import settings


from command.models import Unit, Department
from .models import (
				Profile,
				Team,
				TeamMember,
				Designator,
				Designation,
				)

class ProfileForm(forms.ModelForm):
	class Meta:
		exclude = ('user',)
		model = Profile
		fields = [
			'rank',
			'unit',
			'department',
			'division',
			'phone_number',
			'check_in',
			'prd',
			'force_password_change',
		]
		widgets = { 'check_in': SelectDateWidget(years=range(2010, 2030)),
				   'prd': SelectDateWidget(years=range(2010, 2030)),
				   }

 
class UserForm(forms.ModelForm):
	is_active = forms.BooleanField(required=False)
	password = forms.CharField(widget=forms.PasswordInput)
	password2 = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = [
			'email',
			'first_name',
			'last_name',
		]
		widgets = { 'password': forms.PasswordInput(),
				   'password2': forms.PasswordInput(),
				   }		
	def clean(self):
		password = self.cleaned_data.get('password')
		password2 = self.cleaned_data.get('password2')
	
		if password and password != password2:
			raise forms.ValidationError("Passwords don't match")

		return self.cleaned_data
		
	def clean_email(self):
		data = self.cleaned_data['email']
		domain = data.split('@')[1]
		domain_list = ["navy.mil",]
		if domain not in domain_list:
			raise forms.ValidationError("Please enter an Email Address with a valid domain")
		return data

class TeamForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		self.user = kwargs.pop('user', None)
		self.unit = Unit.objects.filter(profile=self.user.profile)
		super(TeamForm, self).__init__(*args, **kwargs)
		self.fields['department'].queryset = Department.objects.filter(unit=self.unit)  
	class Meta:
		model = Team
		fields = [
			'title',
			'department',
		]      

class TeamMemberForm(forms.ModelForm):
	# def __init__(self, *args, **kwargs):
	# 	self.user = kwargs.pop('user', None)
	# 	super(TeamMemberForm, self).__init__(*args, **kwargs)
	# 	self.fields['member'].queryset = User.objects.filter(profile__unit=self.user.profile.unit)	
	# 	self.fields['title'].empty_label=None
	class Meta:
		model = TeamMember
		fields = [
			'title',
			'member',

		]  


class DesignatorForm(forms.ModelForm):
	class Meta:
		model = Designator
		fields = [
			'code',
			'name',
			'description',

		]
		
class DesignationForm(forms.ModelForm):
	class Meta:
		model = Designation
		fields = [
			'designator',
			'user',

		]

		

src/templates/profiles/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
    
    {% if title %}
    <h1 class='{% if title_align_center %}text-align-center{% endif %}'>{{ title }}</h1>
    {% endif %}
    
    <form  method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
    {{ form|crispy }}

    

    <input class='btn btn-default' type='submit' value='Submit' />
    <a class='btn btn-default' href="{% url 'dashboard:home' %}">Cancel</a>
       
</form>
</div>
</div>
{% endblock %}

src/templates/profiles/profile_main.html
{% extends "base.html" %}
{% load staticfiles %}

{% block navbar %}

         
{% endblock %}


{% block content %}

<div class="page-header row">
	<div class="col-sm-6">
	<h3 style='font-weight: bold; color: #90949c'>Basic Information</h3>
	</div>
	    <div class="col-sm-6">
		  <a type="button" style="text-align: right" class="btn btn-md btn-primary" href="{% url 'profiles:profile_update' pk=profile.pk %}">Edit Profile</a>
		</div>
</div>
<div class="col-sm-8 col-sm-offset-2">
  <div class="thumbnail">
	<div class="caption">
<div class="row">
	<div class="col-sm-6">
	<h4 style='color: #90949c'>Name:</h4>
<hr/>
	</div>
	<div class="col-sm-6">
		<h4 style='color: #90949c'>{{ profile.user.first_name }} {{profile.user.last_name }}</h4>
<hr/>
	</div>
	
</div>

<div class="row">
	<div class="col-sm-6">
	<h4 style='color: #90949c'>Rank:</h4>
<hr/>
	</div>
	<div class="col-sm-6">
		<h4 style='color: #90949c'>{{ profile.rank }}</h4>
<hr/>
	</div>
	
</div>

<div class="row">
	<div class="col-sm-6">
    </hr>    
		{% if profile.user.designation.count > 1 %}
	<h4 style='color: #90949c'>Rates:</h4>
		{% else %}
	<h4 style='color: #90949c'>Rate/Designator:</h4>
		{% endif %}

	</div>
	<div class="col-sm-6">
		{% for designator in profile.user.designation_set.all %}
		{% if designator.count > 1 %}
		<p><h4 style='color: #90949c'>{{ designator }}</h4></p>
		{% else %}
		<h4 style='color: #90949c'>{{ designator.designator.name }}</h4>
		{% endif %}
		{% endfor %}
	</div>
	
</div>
<div class="row">
	<div class="col-sm-6">
<hr/>		
	<h4 style='color: #90949c'>Email:</h4>
<hr/>
	</div>
	<div class="col-sm-6">
<hr/>		
		<h4 style='color: #90949c'>{{ profile.user.email }}</h4>
<hr/>
	</div>
</div>
<div class="row">
	<div class="col-sm-6">
	<h4 style='color: #90949c'>Phone Number:</h4>
	</div>
	<div class="col-sm-6">
     {% if profile.phone_number %}   
		<h4 style='color: #90949c'>{{ profile.phone_number }}</h4>
     {% else %}
     <h4 style='color: #90949c'>None</h4>
     {% endif %}
	</div>
</div>  
	</div>
  </div>
</div>
<div class="col-sm-8 col-sm-offset-2">
  <div class="thumbnail">
	<div class="caption">
<div class="row">
	<div class="col-sm-6">   
	<h4 style='color: #90949c'>Unit:</h4>
	</div>
	<div class="col-sm-6">  
		<h4 style='color: #90949c'>{{ profile.unit.name }}</h4>
	</div>
</div>
<div class="row">    
	<div class="col-sm-6">
        <hr/>     
		{% if profile.department.count > 1 %}
	<h4 style='color: #90949c'>Departments:</h4>
		{% else %}
	<h4 style='color: #90949c'>Department:</h4>
		{% endif %}
	</div>
	<div class="col-sm-6">
    <hr/>     
		{% for department in profile.department.all %}
		{% if department.count > 1 %}
		<p><h4 style='color: #90949c'>{{ department.name }}</h4></p>
		{% else %}
		<h4 style='color: #90949c'>{{ department.name }}</h4>
		{% endif %}
		{% endfor %}
	</div>
</div>
<div class="row">
	<div class="col-sm-6">
    <hr/>         
	<h4 style='color: #90949c'>Check-in Date:</h4>
<hr/>
	</div>
	<div class="col-sm-6">
    <hr/>     
		<h4 style='color: #90949c'>{{ profile.check_in }}</h4>
<hr/>
	</div>
	
</div>

<div class="row">
	<div class="col-sm-6">
	<h4 style='color: #90949c'>PRD:</h4>
	</div>
	<div class="col-sm-6">
		<h4 style='color: #90949c'>{{ profile.prd }}</h4>
	</div>
</div>
	</div>
  </div>
</div>
{% endblock %}

src/templates/profiles/team_confirm_delete.html
{% extends "base.html" %}
{% load staticfiles %}

{% block navbar %}

{% endblock %}


{% block content %}

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete this Team? "{{ object }}"</p>
    <input class='btn btn-danger' type="submit" value="Confirm" />
    <a class='btn btn-default' href="{% url 'profiles:team_main' %}">Cancel</a>
</form>
    </div>

{% endblock %}

src/templates/profiles/team_main.html
{% extends "base.html" %}
{% load staticfiles %}

{% block navbar %}
          <ul class="nav nav-sidebar">
            <li class="active"><a href="{% url 'profiles:team_main' %}">Team Overview <span class="sr-only">(current)</span></a></li>
          </ul>
         
{% endblock %}


{% block content %}

<div class="page-header row">
<div class="col-sm-6 col-sm-offset-2">
  <h1>Team Manager</h1>
  </div>
    {% if perms.profiles.add_team %}
    <div class="row">
      <div class="col-sm-3">  
      <a type="button" class="btn btn-md btn-default" href="{% url 'profiles:team_create' %}">Create Team</a>
      </div>
    </div>
    {% endif %}
</div> 
{% for team in team_list %}
  <div class="col-sm-4 col-md-4">
    <div class="thumbnail">
      <div class="caption">
<div class="row">
	<div class="col-sm-6">
	<h4 style='color: #90949c'>Title:</h4>
<hr/>
	</div>
	<div class="col-sm-6">
		<h4 style='color: #90949c'>{{ team.title }}</h4>
<hr/>
	</div>
</div>
<div class="row">
	<div class="col-sm-6">
	<h4 style='color: #90949c'>Team Leader:</h4>
<hr/>
	</div>
	<div class="col-sm-6">
		<h4 style='color: #90949c'>{{ team.team_lead.profile.rank }} {{ team.team_lead.first_name }} {{ team.team_lead.last_name }}</h4>
<hr/>
	</div>
</div>
<!--Filter Drop Down	-->
<div class="row">
	<div class="col-sm-12">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true"> 
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="{{ team.title }}">
            <h4 class="panel-title">
              <a role="button" data-toggle="collapse" data-parent="#accordion" href="#{{ team.id }}" aria-expanded="false" aria-controls="{{ team.id }}">
                {{ team.title }}
              </a>
            </h4>
          </div>             
          <div id="{{ team.id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="{{ team.title }}">
        <div class="panel-body">
          <!--Members-->

				<div class="list-group">
				{% for member in team.teammember_set.all %}
				 <a type="button" class="list-group-item" href="{% url 'profiles:snivel_master' pk=member.member.profile.pk %}">{{ member.member.profile.rank }} {{ member.member.first_name }} {{ member.member.last_name }}</a>
				{% endfor %}
			   </div>

        </div>
      </div>
  </div>
</div>
</div>
</div>
<div class="row">
	<div class="col-sm-6"> 
  <a type="button" class="btn btn-md btn-primary" href="{% url 'profiles:member_change' pk=team.pk %}">Change Members</a>
  </div>
  {% if perms.profiles.delete_team %}
	<div class="col-sm-6"> 
    <a type="button" class="btn btn-md btn-danger" href="{% url 'profiles:team_delete' pk=team.pk %}">Delete Team</a>
  </div>
  {% endif %}
</div>
	  </div>
	</div>
  </div>
{% endfor %}
{% endblock %}